# .github/release.yml
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - no-changelog
    authors:
      - pre-commit-ci
  categories:
    - title: Breaking Changes 🛠
      labels:
        - "breaking change"
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Config Changes 📑
      labels:
        - config
    - title: Other Changes 🔗
      labels:
        - "*"
