version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
    - (cd docs/scripts && make rst)

sphinx:
  configuration: docs/conf.py

python:
  install:
  - method: pip
    path: .
    extra_requirements:
    - docs
